"use client";

import React, { useState, useEffect } from "react";
import {
  Plus,
  Trash2,
  Save,
  Edit2,
  GripVertical,
  Image as ImageIcon,
  ExternalLink,
} from "lucide-react";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import type { Id } from "../../../../convex/_generated/dataModel";
import { MediaDrawer } from "../components/MediaDrawer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ErrorDisplay } from "../components/ErrorDisplay";
import { SuccessDisplay } from "../components/SuccessDisplay";
import Image from "next/image";

interface Client {
  _id: Id<"clients">;
  name: string;
  url: string;
  logo: string;
  logoAlt?: string;
  order: number;
  createdAt: number;
  updatedAt: number;
}

/* ─── Inline Logo Uploader ───────────────────────────────────────────────── */

/* ─── Main Component ─────────────────────────────────────────────────────── */

const ClientsTabEnhanced = () => {
  const rawClients = useQuery(api.clients.getAll);
  const clientList: Client[] = (rawClients ?? []) as Client[];

  const createClient = useMutation(api.clients.create);
  const updateClient = useMutation(api.clients.update);
  const deleteClientMutation = useMutation(api.clients.deleteClient);
  const reorderClients = useMutation(api.clients.reorder);

  const [selectedClient, setSelectedClient] = useState<Client | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isMediaDrawerOpen, setIsMediaDrawerOpen] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
  const [saveStatus, setSaveStatus] = useState<"success" | "error" | null>(null);

  const [formData, setFormData] = useState({ name: "", url: "", logo: "", logoAlt: "" });

  /* drag-to-reorder state */
  const [draggedId, setDraggedId] = useState<string | null>(null);
  const [dragOverId, setDragOverId] = useState<string | null>(null);

  /* auto-select first client */
  useEffect(() => {
    if (clientList.length > 0 && !selectedClient && !isCreating) {
      setSelectedClient(clientList[0]);
    }
  }, [rawClients, selectedClient, isCreating]);

  /* sync form when selection changes */
  useEffect(() => {
    if (selectedClient && !isCreating) {
      setFormData({
        name: selectedClient.name,
        url: selectedClient.url,
        logo: selectedClient.logo,
        logoAlt: selectedClient.logoAlt ?? `${selectedClient.name} logo`,
      });
      setIsEditing(false);
    }
  }, [selectedClient, isCreating]);

  /* auto-update logoAlt when name changes if alt still matches the generated pattern */
  const handleNameChange = (name: string) => {
    setFormData((p) => {
      const wasAutoGenerated = !p.logoAlt || p.logoAlt === `${p.name} logo`;
      return {
        ...p,
        name,
        logoAlt: wasAutoGenerated ? `${name} logo` : p.logoAlt,
      };
    });
    setIsEditing(true);
  };

  /* ── form handlers ── */

  const handleCreateNew = () => {
    setIsCreating(true);
    setSelectedClient(null);
    setFormData({ name: "", url: "", logo: "", logoAlt: "" });
    setIsEditing(true);
  };

  const handleSave = async () => {
    if (!formData.name.trim() || !formData.url.trim()) {
      setSaveStatus("error");
      return;
    }
    setIsSaving(true);
    try {
      if (isCreating) {
        const nextOrder = clientList.length > 0
          ? Math.max(...clientList.map((c) => c.order)) + 1
          : 0;
        await createClient({
          name: formData.name,
          url: formData.url,
          logo: formData.logo,
          logoAlt: formData.logoAlt || `${formData.name} logo`,
          order: nextOrder,
        });
        setIsCreating(false);
      } else if (selectedClient) {
        await updateClient({
          id: selectedClient._id,
          name: formData.name,
          url: formData.url,
          logo: formData.logo,
          logoAlt: formData.logoAlt || `${formData.name} logo`,
        });
        setSelectedClient((prev) => prev ? { ...prev, ...formData } : null);
      }
      setSaveStatus("success");
      setIsEditing(false);
      setTimeout(() => setSaveStatus(null), 3000);
    } catch {
      setSaveStatus("error");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: Id<"clients">) => {
    try {
      await deleteClientMutation({ id });
      setDeleteConfirm(null);
      if (selectedClient?._id === id) setSelectedClient(null);
      setSaveStatus("success");
      setTimeout(() => setSaveStatus(null), 3000);
    } catch {
      setSaveStatus("error");
    }
  };

  const handleCancel = () => {
    if (isCreating) {
      setIsCreating(false);
      if (clientList.length > 0) setSelectedClient(clientList[0]);
    } else if (selectedClient) {
      setFormData({
        name: selectedClient.name,
        url: selectedClient.url,
        logo: selectedClient.logo,
        logoAlt: selectedClient.logoAlt ?? `${selectedClient.name} logo`,
      });
    }
    setIsEditing(false);
  };

  /* ── drag-to-reorder ── */

  const handleDragStart = (id: string) => setDraggedId(id);
  const handleDragOver = (e: React.DragEvent, id: string) => {
    e.preventDefault();
    if (id !== draggedId) setDragOverId(id);
  };
  const handleDragLeave = () => setDragOverId(null);

  const handleDrop = async (targetId: string) => {
    setDragOverId(null);
    if (!draggedId || draggedId === targetId) return;

    const ordered = [...clientList];
    const fromIdx = ordered.findIndex((c) => c._id === draggedId);
    const toIdx = ordered.findIndex((c) => c._id === targetId);
    if (fromIdx === -1 || toIdx === -1) return;

    const [moved] = ordered.splice(fromIdx, 1);
    ordered.splice(toIdx, 0, moved);

    const updates = ordered.map((c, i) => ({ id: c._id, order: i }));
    await reorderClients({ items: updates });
    setDraggedId(null);
  };

  const handleDragEnd = () => {
    setDraggedId(null);
    setDragOverId(null);
  };

  return (
    <div className="grid grid-cols-3 gap-6 h-full">
      {/* ── Left: Client List ── */}
      <div className="bg-(--color-panel) border border-(--color-border) rounded-2xl p-4 flex flex-col">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold text-(--color-ink)">Clients</h3>
          <Button onClick={handleCreateNew} variant="accent" size="sm" className="gap-2">
            <Plus className="w-4 h-4" />
            New
          </Button>
        </div>

        <p className="text-xs text-muted mb-3">Drag to reorder</p>

        <div className="flex-1 overflow-y-auto space-y-1.5">
          {clientList.map((client) => (
            <div
              key={client._id}
              draggable
              onDragStart={() => handleDragStart(client._id)}
              onDragOver={(e) => handleDragOver(e, client._id)}
              onDragLeave={handleDragLeave}
              onDrop={() => handleDrop(client._id)}
              onDragEnd={handleDragEnd}
              onClick={() => {
                setSelectedClient(client);
                setIsCreating(false);
                setIsEditing(false);
              }}
              className={`flex items-center gap-2 p-2.5 rounded-lg cursor-pointer transition-all
                ${dragOverId === client._id ? "border-2 border-accent bg-accent/5" : "border border-transparent"}
                ${draggedId === client._id ? "opacity-40" : ""}
                ${selectedClient?._id === client._id && !isCreating
                  ? "bg-(--color-foreground) text-(--color-panel)"
                  : "bg-(--color-muted-accent) hover:bg-(--color-surface-hover) text-(--color-ink)"
                }`}
            >
              <GripVertical className="w-4 h-4 shrink-0 text-muted cursor-grab" />
              {client.logo && (
                <div className="relative w-8 h-8 shrink-0 rounded overflow-hidden bg-(--color-panel)">
                  <Image
                    src={client.logo}
                    alt={client.name}
                    fill
                    sizes="32px"
                    className="object-contain p-0.5"
                  />
                </div>
              )}
              <span className="text-sm font-medium truncate flex-1">{client.name}</span>
            </div>
          ))}

          {clientList.length === 0 && (
            <p className="text-sm text-muted text-center py-8">
              No clients yet. Click + New to add one.
            </p>
          )}
        </div>
      </div>

      {/* ── Right: Detail / Form ── */}
      <div className="col-span-2 bg-(--color-panel) border border-(--color-border) rounded-2xl overflow-hidden flex flex-col">
        {saveStatus === "success" && (
          <div className="px-6 pt-4">
            <SuccessDisplay message="Client saved!" onDismiss={() => setSaveStatus(null)} compact />
          </div>
        )}
        {saveStatus === "error" && (
          <div className="px-6 pt-4">
            <ErrorDisplay
              error={new Error(!formData.name.trim() || !formData.url.trim() ? "Name and URL are required" : "Failed to save client")}
              onDismiss={() => setSaveStatus(null)}
              compact
            />
          </div>
        )}

        {(selectedClient || isCreating) ? (
          <>
            {/* Banner */}
            <div className="flex items-center justify-between px-6 py-4 bg-(--color-muted-accent) shrink-0">
              <div className="flex items-center gap-3 min-w-0">
                {formData.logo && (
                  <div className="relative w-10 h-10 shrink-0 rounded-lg overflow-hidden bg-(--color-panel)">
                    <Image
                      src={formData.logo}
                      alt={formData.name}
                      fill
                      sizes="40px"
                      className="object-contain p-1"
                    />
                  </div>
                )}
                <div className="min-w-0">
                  <h2 className="font-bold text-ink truncate">
                    {isCreating ? "New Client" : formData.name || "Untitled"}
                  </h2>
                  {formData.url && (
                    <p className="text-sm text-muted truncate">{formData.url}</p>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                {isEditing ? (
                  <>
                    <Button onClick={handleCancel} variant="outline" size="sm">
                      Cancel
                    </Button>
                    <Button
                      onClick={handleSave}
                      variant="accent"
                      size="sm"
                      className="gap-2"
                      disabled={isSaving}
                    >
                      <Save className="w-4 h-4" />
                      {isSaving ? "Saving…" : "Save"}
                    </Button>
                  </>
                ) : (
                  <>
                    <Button
                      onClick={() => setIsEditing(true)}
                      variant="outline"
                      size="sm"
                      className="gap-2"
                    >
                      <Edit2 className="w-4 h-4" />
                      Edit
                    </Button>
                    {selectedClient && (
                      <Button
                        onClick={() => setDeleteConfirm(selectedClient._id)}
                        variant="outline"
                        size="sm"
                        className="text-red-500 hover:text-red-600 hover:bg-red-500/10"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    )}
                    {formData.url && (
                      <a
                        href={formData.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="p-2 text-muted hover:text-ink transition rounded-lg hover:bg-(--color-muted-accent)"
                      >
                        <ExternalLink className="w-4 h-4" />
                      </a>
                    )}
                  </>
                )}
              </div>
            </div>

            {/* Form */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6">
              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">
                  Company Name <span className="text-red-500">*</span>
                </label>
                <Input
                  value={formData.name}
                  onChange={(e) => handleNameChange(e.target.value)}
                  disabled={!isEditing}
                  placeholder="Acme Corporation"
                />
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">
                  Website URL <span className="text-red-500">*</span>
                </label>
                <Input
                  value={formData.url}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, url: e.target.value }));
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder="https://acme.com"
                />
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Logo Alt Text</label>
                <Input
                  value={formData.logoAlt}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, logoAlt: e.target.value }));
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder={formData.name ? `${formData.name} logo` : "Company Name logo"}
                />
                <p className="text-xs text-muted">Auto-generated from company name. Edit to customise.</p>
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Logo Image</label>
                {formData.logo ? (
                  <div
                    className={`relative w-full h-40 rounded-xl border border-(--color-border) overflow-hidden bg-(--color-muted-accent) ${isEditing ? "cursor-pointer group" : ""}`}
                    onClick={isEditing ? () => setIsMediaDrawerOpen(true) : undefined}
                  >
                    <Image
                      src={formData.logo}
                      alt={formData.name}
                      fill
                      sizes="400px"
                      className="object-contain p-4"
                    />
                    {isEditing && (
                      <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 bg-black/30 rounded-xl transition-opacity">
                        <span className="bg-(--color-panel) rounded-lg px-3 py-2 text-sm font-medium text-ink">
                          Change Image
                        </span>
                      </div>
                    )}
                  </div>
                ) : (
                  <div
                    className={`h-40 rounded-xl border-2 border-dashed border-(--color-border) bg-(--color-muted-accent) flex items-center justify-center ${isEditing ? "cursor-pointer hover:border-accent hover:bg-accent/5 transition-all" : ""}`}
                    onClick={isEditing ? () => setIsMediaDrawerOpen(true) : undefined}
                  >
                    <div className="flex flex-col items-center gap-2 text-muted">
                      <ImageIcon className="w-8 h-8" />
                      <span className="text-sm">{isEditing ? "Select Image for Featured Slot" : "No image set"}</span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center text-muted">
            <div className="text-center">
              <ImageIcon className="w-12 h-12 mx-auto opacity-40 mb-4" />
              <p>Select a client to view or edit</p>
            </div>
          </div>
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-(--color-panel) rounded-2xl p-6 max-w-sm w-full border border-(--color-border)">
            <h3 className="text-lg font-bold text-ink mb-4">Delete Client?</h3>
            <p className="text-muted mb-6">This cannot be undone.</p>
            <div className="flex gap-2">
              <Button
                onClick={() => handleDelete(deleteConfirm as Id<"clients">)}
                variant="outline"
                className="flex-1 text-red-500"
              >
                Delete
              </Button>
              <Button
                onClick={() => setDeleteConfirm(null)}
                variant="outline"
                className="flex-1"
              >
                Cancel
              </Button>
            </div>
          </div>
        </div>
      )}

      <MediaDrawer
        isOpen={isMediaDrawerOpen}
        onClose={() => setIsMediaDrawerOpen(false)}
        onSelect={(url) => {
          setFormData((p) => ({ ...p, logo: url }));
          setIsEditing(true);
          setIsMediaDrawerOpen(false);
        }}
        title="Select Image for Featured Slot"
        description="Choose an image from your media library or upload a new one"
      />
    </div>
  );
};

export default ClientsTabEnhanced;
