"use client";

import React, { useState, useEffect } from "react";
import {
  Plus,
  Trash2,
  Save,
  Edit2,
  Image as ImageIcon,
  ExternalLink,
  MapPin,
  Calendar,
} from "lucide-react";
import { useQuery, useMutation } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import type { Id } from "../../../../convex/_generated/dataModel";
import { MediaDrawer } from "../components/MediaDrawer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ErrorDisplay } from "../components/ErrorDisplay";
import { SuccessDisplay } from "../components/SuccessDisplay";
import Image from "next/image";

interface Conference {
  _id: Id<"conferences">;
  slug: string;
  name: string;
  year: number;
  dateStart?: string;
  dateEnd?: string;
  city?: string;
  venue?: string;
  url?: string;
  description?: string;
  tags?: string[];
  logo?: string;
  logoAlt?: string;
  createdAt: number;
  updatedAt: number;
}

interface FormData {
  slug: string;
  name: string;
  year: string;
  dateStart: string;
  dateEnd: string;
  city: string;
  venue: string;
  url: string;
  description: string;
  tags: string;
  logo: string;
  logoAlt: string;
}

const emptyForm: FormData = {
  slug: "",
  name: "",
  year: new Date().getFullYear().toString(),
  dateStart: "",
  dateEnd: "",
  city: "",
  venue: "",
  url: "",
  description: "",
  tags: "",
  logo: "",
  logoAlt: "",
};

function toForm(c: Conference): FormData {
  return {
    slug: c.slug,
    name: c.name,
    year: String(c.year),
    dateStart: c.dateStart ?? "",
    dateEnd: c.dateEnd ?? "",
    city: c.city ?? "",
    venue: c.venue ?? "",
    url: c.url ?? "",
    description: c.description ?? "",
    tags: (c.tags ?? []).join(", "),
    logo: c.logo ?? "",
    logoAlt: c.logoAlt ?? `${c.name} logo`,
  };
}

function slugify(name: string, year: string): string {
  return `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${year}`;
}

const ConferencesTabEnhanced = () => {
  const rawConferences = useQuery(api.conferences.getAll);
  const confList: Conference[] = (rawConferences ?? []) as Conference[];

  const createConference = useMutation(api.conferences.create);
  const updateConference = useMutation(api.conferences.update);
  const deleteConferenceMutation = useMutation(api.conferences.deleteConference);
  const seedConferences = useMutation(api.conferences.seedConferences);

  const [selected, setSelected] = useState<Conference | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isSeeding, setIsSeeding] = useState(false);
  const [isMediaDrawerOpen, setIsMediaDrawerOpen] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
  const [saveStatus, setSaveStatus] = useState<"success" | "error" | null>(null);
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [formData, setFormData] = useState<FormData>(emptyForm);

  useEffect(() => {
    if (confList.length > 0 && !selected && !isCreating) {
      setSelected(confList[0]);
    }
  }, [rawConferences, selected, isCreating]);

  useEffect(() => {
    if (selected && !isCreating) {
      setFormData(toForm(selected));
      setSlugAutoGenerated(false);
      setIsEditing(false);
    }
  }, [selected, isCreating]);

  const handleNameChange = (name: string) => {
    setFormData((p) => {
      const newSlug = slugAutoGenerated ? slugify(name, p.year) : p.slug;
      const wasAutoAlt = !p.logoAlt || p.logoAlt === `${p.name} logo`;
      return {
        ...p,
        name,
        slug: newSlug,
        logoAlt: wasAutoAlt ? `${name} logo` : p.logoAlt,
      };
    });
    setIsEditing(true);
  };

  const handleYearChange = (year: string) => {
    setFormData((p) => {
      const newSlug = slugAutoGenerated ? slugify(p.name, year) : p.slug;
      return { ...p, year, slug: newSlug };
    });
    setIsEditing(true);
  };

  const handleCreateNew = () => {
    setIsCreating(true);
    setSelected(null);
    setFormData(emptyForm);
    setSlugAutoGenerated(true);
    setIsEditing(true);
  };

  const handleSave = async () => {
    if (!formData.name.trim()) {
      setSaveStatus("error");
      return;
    }
    setIsSaving(true);
    try {
      const payload = {
        slug: formData.slug || slugify(formData.name, formData.year),
        name: formData.name,
        year: parseInt(formData.year, 10) || new Date().getFullYear(),
        dateStart: formData.dateStart || undefined,
        dateEnd: formData.dateEnd || undefined,
        city: formData.city || undefined,
        venue: formData.venue || undefined,
        url: formData.url || undefined,
        description: formData.description || undefined,
        tags: formData.tags ? formData.tags.split(",").map((t) => t.trim()).filter(Boolean) : undefined,
        logo: formData.logo || undefined,
        logoAlt: formData.logoAlt || `${formData.name} logo`,
      };

      if (isCreating) {
        await createConference(payload);
        setIsCreating(false);
      } else if (selected) {
        await updateConference({ id: selected._id, ...payload });
        setSelected((prev) => prev ? { ...prev, ...payload, _id: prev._id, createdAt: prev.createdAt, updatedAt: Date.now() } : null);
      }
      setSaveStatus("success");
      setIsEditing(false);
      setTimeout(() => setSaveStatus(null), 3000);
    } catch {
      setSaveStatus("error");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: Id<"conferences">) => {
    try {
      await deleteConferenceMutation({ id });
      setDeleteConfirm(null);
      if (selected?._id === id) setSelected(null);
      setSaveStatus("success");
      setTimeout(() => setSaveStatus(null), 3000);
    } catch {
      setSaveStatus("error");
    }
  };

  const handleCancel = () => {
    if (isCreating) {
      setIsCreating(false);
      if (confList.length > 0) setSelected(confList[0]);
    } else if (selected) {
      setFormData(toForm(selected));
    }
    setIsEditing(false);
  };

  const handleSeed = async () => {
    setIsSeeding(true);
    try {
      await seedConferences({});
      setSaveStatus("success");
      setTimeout(() => setSaveStatus(null), 3000);
    } catch {
      setSaveStatus("error");
    } finally {
      setIsSeeding(false);
    }
  };

  const formatDateRange = (c: Conference) => {
    if (!c.dateStart) return String(c.year);
    const start = new Date(c.dateStart + "T12:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" });
    if (!c.dateEnd) return `${start}, ${c.year}`;
    const end = new Date(c.dateEnd + "T12:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" });
    return `${start}–${end}, ${c.year}`;
  };

  return (
    <div className="grid grid-cols-3 gap-6 h-full">
      {/* ── Left: Conference List ── */}
      <div className="bg-(--color-panel) border border-(--color-border) rounded-2xl p-4 flex flex-col">
        <div className="flex items-center justify-between mb-3">
          <h3 className="font-semibold text-(--color-ink)">Conferences</h3>
          <Button onClick={handleCreateNew} variant="accent" size="sm" className="gap-2">
            <Plus className="w-4 h-4" />
            New
          </Button>
        </div>

        <p className="text-xs text-muted mb-3">Sorted by date, most recent first</p>

        <div className="flex-1 overflow-y-auto space-y-1.5">
          {confList.map((conf) => (
            <div
              key={conf._id}
              onClick={() => {
                setSelected(conf);
                setIsCreating(false);
                setIsEditing(false);
              }}
              className={`flex items-center gap-2 p-2.5 rounded-lg cursor-pointer transition-all border border-transparent
                ${selected?._id === conf._id && !isCreating
                  ? "bg-(--color-foreground) text-(--color-panel)"
                  : "bg-(--color-muted-accent) hover:bg-(--color-surface-hover) text-(--color-ink)"
                }`}
            >
              {conf.logo ? (
                <div className="relative w-8 h-8 shrink-0 rounded overflow-hidden bg-(--color-panel)">
                  <Image
                    src={conf.logo}
                    alt={conf.name}
                    fill
                    sizes="32px"
                    className="object-contain p-0.5"
                  />
                </div>
              ) : (
                <div className="w-8 h-8 shrink-0 rounded bg-(--color-border) flex items-center justify-center">
                  <Calendar className="w-4 h-4 opacity-50" />
                </div>
              )}
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium truncate">{conf.name}</p>
                <p className="text-xs opacity-60 truncate">{formatDateRange(conf)}</p>
              </div>
            </div>
          ))}

          {confList.length === 0 && (
            <div className="text-center py-8 space-y-3">
              <p className="text-sm text-muted">No conferences yet.</p>
              <Button
                onClick={handleSeed}
                variant="outline"
                size="sm"
                disabled={isSeeding}
              >
                {isSeeding ? "Seeding…" : "Seed from data file"}
              </Button>
            </div>
          )}
        </div>

        {confList.length > 0 && (
          <div className="mt-3 pt-3 border-t border-(--color-border)">
            <Button
              onClick={handleSeed}
              variant="outline"
              size="sm"
              className="w-full text-xs"
              disabled={isSeeding}
            >
              {isSeeding ? "Seeding…" : "Re-seed from data file"}
            </Button>
          </div>
        )}
      </div>

      {/* ── Right: Detail / Form ── */}
      <div className="col-span-2 bg-(--color-panel) border border-(--color-border) rounded-2xl overflow-hidden flex flex-col">
        {saveStatus === "success" && (
          <div className="px-6 pt-4">
            <SuccessDisplay message="Conference saved!" onDismiss={() => setSaveStatus(null)} compact />
          </div>
        )}
        {saveStatus === "error" && (
          <div className="px-6 pt-4">
            <ErrorDisplay
              error={new Error(!formData.name.trim() ? "Conference name is required" : "Failed to save conference")}
              onDismiss={() => setSaveStatus(null)}
              compact
            />
          </div>
        )}

        {(selected || isCreating) ? (
          <>
            {/* Banner */}
            <div className="flex items-center justify-between px-6 py-4 bg-(--color-muted-accent) shrink-0">
              <div className="flex items-center gap-3 min-w-0">
                {formData.logo && (
                  <div className="relative w-10 h-10 shrink-0 rounded-lg overflow-hidden bg-(--color-panel)">
                    <Image
                      src={formData.logo}
                      alt={formData.name}
                      fill
                      sizes="40px"
                      className="object-contain p-1"
                    />
                  </div>
                )}
                <div className="min-w-0">
                  <h2 className="font-bold text-ink truncate">
                    {isCreating ? "New Conference" : formData.name || "Untitled"}
                  </h2>
                  {(formData.city || formData.dateStart) && (
                    <p className="text-sm text-muted truncate flex items-center gap-1">
                      <MapPin className="w-3 h-3 shrink-0" />
                      {[formData.city, formData.dateStart ? formData.year : ""].filter(Boolean).join(" · ")}
                    </p>
                  )}
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                {isEditing ? (
                  <>
                    <Button onClick={handleCancel} variant="outline" size="sm">
                      Cancel
                    </Button>
                    <Button
                      onClick={handleSave}
                      variant="accent"
                      size="sm"
                      className="gap-2"
                      disabled={isSaving}
                    >
                      <Save className="w-4 h-4" />
                      {isSaving ? "Saving…" : "Save"}
                    </Button>
                  </>
                ) : (
                  <>
                    <Button
                      onClick={() => setIsEditing(true)}
                      variant="outline"
                      size="sm"
                      className="gap-2"
                    >
                      <Edit2 className="w-4 h-4" />
                      Edit
                    </Button>
                    {selected && (
                      <Button
                        onClick={() => setDeleteConfirm(selected._id)}
                        variant="outline"
                        size="sm"
                        className="text-red-500 hover:text-red-600 hover:bg-red-500/10"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    )}
                    {formData.url && (
                      <a
                        href={formData.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="p-2 text-muted hover:text-ink transition rounded-lg hover:bg-(--color-muted-accent)"
                      >
                        <ExternalLink className="w-4 h-4" />
                      </a>
                    )}
                  </>
                )}
              </div>
            </div>

            {/* Form */}
            <div className="flex-1 overflow-y-auto p-6 space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-ink">
                    Conference Name <span className="text-red-500">*</span>
                  </label>
                  <Input
                    value={formData.name}
                    onChange={(e) => handleNameChange(e.target.value)}
                    disabled={!isEditing}
                    placeholder="All Things Open"
                  />
                </div>
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-ink">Year</label>
                  <Input
                    type="number"
                    value={formData.year}
                    onChange={(e) => handleYearChange(e.target.value)}
                    disabled={!isEditing}
                    placeholder="2025"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-ink">Start Date</label>
                  <Input
                    type="date"
                    value={formData.dateStart}
                    onChange={(e) => {
                      setFormData((p) => ({ ...p, dateStart: e.target.value }));
                      setIsEditing(true);
                    }}
                    disabled={!isEditing}
                  />
                </div>
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-ink">End Date</label>
                  <Input
                    type="date"
                    value={formData.dateEnd}
                    onChange={(e) => {
                      setFormData((p) => ({ ...p, dateEnd: e.target.value }));
                      setIsEditing(true);
                    }}
                    disabled={!isEditing}
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-ink">City</label>
                  <Input
                    value={formData.city}
                    onChange={(e) => {
                      setFormData((p) => ({ ...p, city: e.target.value }));
                      setIsEditing(true);
                    }}
                    disabled={!isEditing}
                    placeholder="Raleigh, NC"
                  />
                </div>
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-ink">Venue</label>
                  <Input
                    value={formData.venue}
                    onChange={(e) => {
                      setFormData((p) => ({ ...p, venue: e.target.value }));
                      setIsEditing(true);
                    }}
                    disabled={!isEditing}
                    placeholder="Raleigh Convention Center"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Website URL</label>
                <Input
                  value={formData.url}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, url: e.target.value }));
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder="https://conference.example.com"
                />
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Tags / Topics</label>
                <Input
                  value={formData.tags}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, tags: e.target.value }));
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder="React, TypeScript, Open Source"
                />
                <p className="text-xs text-muted">Comma-separated list of topics.</p>
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Description</label>
                <Textarea
                  value={formData.description}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, description: e.target.value }));
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder="Brief summary of the conference…"
                  rows={4}
                />
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Slug</label>
                <Input
                  value={formData.slug}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, slug: e.target.value }));
                    setSlugAutoGenerated(false);
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder="all-things-open-2025"
                />
                <p className="text-xs text-muted">Auto-generated from name + year. Used in the public URL.</p>
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Logo Alt Text</label>
                <Input
                  value={formData.logoAlt}
                  onChange={(e) => {
                    setFormData((p) => ({ ...p, logoAlt: e.target.value }));
                    setIsEditing(true);
                  }}
                  disabled={!isEditing}
                  placeholder={formData.name ? `${formData.name} logo` : "Conference logo"}
                />
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-ink">Logo / Cover Image</label>
                {formData.logo ? (
                  <div
                    className={`relative w-full h-48 rounded-xl border border-(--color-border) overflow-hidden bg-(--color-muted-accent) ${isEditing ? "cursor-pointer group" : ""}`}
                    onClick={isEditing ? () => setIsMediaDrawerOpen(true) : undefined}
                  >
                    <Image
                      src={formData.logo}
                      alt={formData.logoAlt || formData.name}
                      fill
                      sizes="600px"
                      className="object-contain p-6"
                    />
                    {isEditing && (
                      <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 bg-black/30 rounded-xl transition-opacity">
                        <span className="bg-(--color-panel) rounded-lg px-3 py-2 text-sm font-medium text-ink">
                          Change Image
                        </span>
                      </div>
                    )}
                  </div>
                ) : (
                  <div
                    className={`h-48 rounded-xl border-2 border-dashed border-(--color-border) bg-(--color-muted-accent) flex items-center justify-center ${isEditing ? "cursor-pointer hover:border-accent hover:bg-accent/5 transition-all" : ""}`}
                    onClick={isEditing ? () => setIsMediaDrawerOpen(true) : undefined}
                  >
                    <div className="flex flex-col items-center gap-2 text-muted">
                      <ImageIcon className="w-8 h-8" />
                      <span className="text-sm">{isEditing ? "Select Logo from Media Library" : "No logo set"}</span>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center text-muted">
            <div className="text-center">
              <Calendar className="w-12 h-12 mx-auto opacity-40 mb-4" />
              <p>Select a conference to view or edit</p>
            </div>
          </div>
        )}
      </div>

      {/* Delete Confirmation Modal */}
      {deleteConfirm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-(--color-panel) rounded-2xl p-6 max-w-sm w-full border border-(--color-border)">
            <h3 className="text-lg font-bold text-ink mb-4">Delete Conference?</h3>
            <p className="text-muted mb-6">This cannot be undone.</p>
            <div className="flex gap-2">
              <Button
                onClick={() => handleDelete(deleteConfirm as Id<"conferences">)}
                variant="outline"
                className="flex-1 text-red-500"
              >
                Delete
              </Button>
              <Button
                onClick={() => setDeleteConfirm(null)}
                variant="outline"
                className="flex-1"
              >
                Cancel
              </Button>
            </div>
          </div>
        </div>
      )}

      <MediaDrawer
        isOpen={isMediaDrawerOpen}
        onClose={() => setIsMediaDrawerOpen(false)}
        onSelect={(url) => {
          setFormData((p) => ({ ...p, logo: url }));
          setIsEditing(true);
          setIsMediaDrawerOpen(false);
        }}
        title="Select Conference Logo"
        description="Choose an image from your media library or upload a new one"
      />
    </div>
  );
};

export default ConferencesTabEnhanced;
